# Generated by Django 6.0.6 on 2026-07-07 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('ragione_sociale', models.CharField(max_length=200, verbose_name='Ragione sociale')),
                ('partita_iva', models.CharField(blank=True, max_length=20, verbose_name='Partita IVA')),
                ('codice_fiscale', models.CharField(blank=True, max_length=20, verbose_name='Codice Fiscale')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Anagrafica',
                'verbose_name_plural': 'Anagrafiche',
                'ordering': ['ragione_sociale'],
            },
        ),
    ]
