# Generated by Django 6.0.6 on 2026-07-07 18:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_uuid(apps, schema_editor):
    Anagrafica = apps.get_model("anagrafiche", "Anagrafica")
    for anagrafica in Anagrafica.objects.filter(uuid__isnull=True):
        anagrafica.uuid = uuid.uuid4()
        anagrafica.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anagrafica",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Eliminato il"),
        ),
        migrations.AddField(
            model_name="anagrafica",
            name="deleted_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_deleted", to=settings.AUTH_USER_MODEL, verbose_name="Eliminato da"),
        ),
        migrations.AddField(
            model_name="anagrafica",
            name="note",
            field=models.TextField(blank=True, verbose_name="Note"),
        ),
        migrations.AddField(
            model_name="anagrafica",
            name="uuid",
            field=models.UUIDField(editable=False, null=True, verbose_name="UUID"),
        ),
        migrations.RunPython(populate_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="anagrafica",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"),
        ),
    ]
