# Generated by Django 6.0.6 on 2026-07-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anagrafiche',
            options={'ordering': ['ragione_sociale'], 'verbose_name': 'Azienda', 'verbose_name_plural': 'Aziende'},
        ),
        migrations.AddField(
            model_name='anagrafiche',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='anagrafiche',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='anagrafiche',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=20, verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='anagrafiche',
            name='partita_iva',
            field=models.CharField(blank=True, max_length=20, verbose_name='Partita IVA'),
        ),
        migrations.AlterField(
            model_name='anagrafiche',
            name='ragione_sociale',
            field=models.CharField(max_length=200, verbose_name='Ragione sociale'),
        ),
    ]
