# Generated by Django 6.0.6 on 2026-07-07 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0002_anagrafica_deleted_at_anagrafica_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('telefono', 'Telefono'), ('cellulare', 'Cellulare'), ('pec', 'PEC'), ('sito_web', 'Sito web'), ('altro', 'Altro')], default='email', max_length=20, verbose_name='Tipo')),
                ('valore', models.CharField(max_length=255, verbose_name='Valore')),
                ('descrizione', models.CharField(blank=True, help_text='Esempio: amministrazione, ufficio tecnico, referente privacy.', max_length=100, verbose_name='Descrizione')),
                ('principale', models.BooleanField(default=False, verbose_name='Principale')),
                ('anagrafica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatti', to='anagrafiche.anagrafica', verbose_name='Anagrafica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Contatto',
                'verbose_name_plural': 'Contatti',
                'ordering': ['anagrafica__ragione_sociale', '-principale', 'tipo', 'valore'],
            },
        ),
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('tipo', models.CharField(choices=[('sede_legale', 'Sede legale'), ('sede_operativa', 'Sede operativa'), ('fatturazione', 'Fatturazione'), ('spedizione', 'Spedizione'), ('altro', 'Altro')], default='sede_operativa', max_length=30, verbose_name='Tipo')),
                ('indirizzo', models.CharField(max_length=255, verbose_name='Indirizzo')),
                ('civico', models.CharField(blank=True, max_length=20, verbose_name='Civico')),
                ('cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('comune', models.CharField(blank=True, max_length=100, verbose_name='Comune')),
                ('provincia', models.CharField(blank=True, max_length=2, verbose_name='Provincia')),
                ('nazione', models.CharField(default='Italia', max_length=100, verbose_name='Nazione')),
                ('principale', models.BooleanField(default=False, verbose_name='Principale')),
                ('anagrafica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzi', to='anagrafiche.anagrafica', verbose_name='Anagrafica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Indirizzo',
                'verbose_name_plural': 'Indirizzi',
                'ordering': ['anagrafica__ragione_sociale', '-principale', 'tipo'],
            },
        ),
    ]
