# Generated by Django 6.0.6 on 2026-07-08 00:26

import apps.anagrafiche.models.anagrafica
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_contatto_indirizzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='logo',
            field=models.FileField(blank=True, upload_to=apps.anagrafiche.models.anagrafica.anagrafica_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'svg'])], verbose_name='Logo'),
        ),
    ]
