from django.urls import path

from apps.pratiche.views import (
    CategoriaPraticaCreateView,
    CategoriaPraticaDeleteView,
    CategoriaPraticaListView,
    CategoriaPraticaUpdateView,
    ComunicazionePraticaCreateView,
    ComunicazionePraticaFileView,
    ComunicazionePraticaPreviewView,
    FolderPickerView,
    FolderPreviewFileDeleteView,
    FolderPreviewFileOpenView,
    FolderPreviewView,
    IncaricoTecnicoCreateView,
    IncaricoTecnicoDeleteView,
    IncaricoTecnicoListView,
    IncaricoTecnicoUpdateView,
    MacroCategoriaPraticaCreateView,
    MacroCategoriaPraticaDeleteView,
    MacroCategoriaPraticaListView,
    MacroCategoriaPraticaUpdateView,
    PraticaCreateView,
    PraticaCategoriaAllegatoDeleteView,
    PraticaCategoriaAllegatoDestroyView,
    PraticaCategoriaAllegatoFileView,
    PraticaCategoriaAllegatoOpenView,
    PraticaCategoriaAllegatoPickView,
    PraticaCategoriaAllegatoUploadView,
    PraticaCategoriaCreateView,
    PraticaCategoriaDeleteView,
    PraticaCategoriaFileDeleteView,
    PraticaCategoriaFileDescriptionView,
    PraticaCategoriaFileOpenView,
    PraticaCategoriaFileUnlinkView,
    PraticaCategoriaFileUploadView,
    PraticaCategoriaFileView,
    PraticaCategoriaUpdateView,
    PraticaDeleteView,
    PraticaDetailView,
    PraticaListView,
    PraticaMacroCategoriaApplyView,
    PraticaUpdateView,
    StudioTecnicoCreateView,
    StudioTecnicoDeleteView,
    StudioTecnicoListView,
    StudioTecnicoUpdateView,
    TecnicoCreateView,
    TecnicoDeleteView,
    TecnicoUpdateView,
    TemplatePraticaCreateView,
    TemplatePraticaDeleteView,
    TemplatePraticaListView,
    TemplatePraticaRowsView,
    TemplatePraticaUpdateView,
)

app_name = "pratiche"

urlpatterns = [
    path("", PraticaListView.as_view(), name="pratica_list"),
    path("nuova/", PraticaCreateView.as_view(), name="pratica_create"),
    path("cartelle/scegli/", FolderPickerView.as_view(), name="folder_picker"),
    path("cartelle/anteprima/", FolderPreviewView.as_view(), name="folder_preview"),
    path("cartelle/anteprima/file/apri/", FolderPreviewFileOpenView.as_view(), name="folder_preview_file_open"),
    path("cartelle/anteprima/file/elimina/", FolderPreviewFileDeleteView.as_view(), name="folder_preview_file_delete"),
    path("<int:pk>/", PraticaDetailView.as_view(), name="pratica_detail"),
    path("<int:pk>/modifica/", PraticaUpdateView.as_view(), name="pratica_update"),
    path("<int:pk>/elimina/", PraticaDeleteView.as_view(), name="pratica_delete"),
    path("<int:pratica_pk>/comunicazioni/nuova/", ComunicazionePraticaCreateView.as_view(), name="comunicazione_create"),
    path("<int:pratica_pk>/comunicazioni/<int:pk>/anteprima/", ComunicazionePraticaPreviewView.as_view(), name="comunicazione_preview"),
    path("<int:pratica_pk>/comunicazioni/<int:pk>/file/", ComunicazionePraticaFileView.as_view(), name="comunicazione_file"),
    path("categorie/", CategoriaPraticaListView.as_view(), name="categoria_pratica_list"),
    path("categorie/nuova/", CategoriaPraticaCreateView.as_view(), name="categoria_pratica_create"),
    path("categorie/<int:pk>/modifica/", CategoriaPraticaUpdateView.as_view(), name="categoria_pratica_update"),
    path("categorie/<int:pk>/elimina/", CategoriaPraticaDeleteView.as_view(), name="categoria_pratica_delete"),
    path("macro-categorie/", MacroCategoriaPraticaListView.as_view(), name="macro_categoria_pratica_list"),
    path("macro-categorie/nuova/", MacroCategoriaPraticaCreateView.as_view(), name="macro_categoria_pratica_create"),
    path("macro-categorie/<int:pk>/modifica/", MacroCategoriaPraticaUpdateView.as_view(), name="macro_categoria_pratica_update"),
    path("macro-categorie/<int:pk>/elimina/", MacroCategoriaPraticaDeleteView.as_view(), name="macro_categoria_pratica_delete"),
    path("template-pratiche/", TemplatePraticaListView.as_view(), name="template_pratica_list"),
    path("template-pratiche/righe/", TemplatePraticaRowsView.as_view(), name="template_pratica_rows"),
    path("template-pratiche/nuovo/", TemplatePraticaCreateView.as_view(), name="template_pratica_create"),
    path("template-pratiche/<int:pk>/modifica/", TemplatePraticaUpdateView.as_view(), name="template_pratica_update"),
    path("template-pratiche/<int:pk>/elimina/", TemplatePraticaDeleteView.as_view(), name="template_pratica_delete"),
    path("studi-tecnici/", StudioTecnicoListView.as_view(), name="studio_tecnico_list"),
    path("studi-tecnici/nuovo/", StudioTecnicoCreateView.as_view(), name="studio_tecnico_create"),
    path("studi-tecnici/<int:pk>/modifica/", StudioTecnicoUpdateView.as_view(), name="studio_tecnico_update"),
    path("studi-tecnici/<int:pk>/elimina/", StudioTecnicoDeleteView.as_view(), name="studio_tecnico_delete"),
    path("incarichi/", IncaricoTecnicoListView.as_view(), name="incarico_tecnico_list"),
    path("incarichi/nuovo/", IncaricoTecnicoCreateView.as_view(), name="incarico_tecnico_create"),
    path("incarichi/<int:pk>/modifica/", IncaricoTecnicoUpdateView.as_view(), name="incarico_tecnico_update"),
    path("incarichi/<int:pk>/elimina/", IncaricoTecnicoDeleteView.as_view(), name="incarico_tecnico_delete"),
    path("<int:pratica_pk>/categorie/nuova/", PraticaCategoriaCreateView.as_view(), name="pratica_categoria_create"),
    path("<int:pratica_pk>/macro-categorie/applica/", PraticaMacroCategoriaApplyView.as_view(), name="pratica_macro_categoria_apply"),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/modifica/",
        PraticaCategoriaUpdateView.as_view(),
        name="pratica_categoria_update",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/elimina/",
        PraticaCategoriaDeleteView.as_view(),
        name="pratica_categoria_delete",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/",
        PraticaCategoriaFileView.as_view(),
        name="pratica_categoria_file",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/apri/",
        PraticaCategoriaFileOpenView.as_view(),
        name="pratica_categoria_file_open",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/aggiungi/",
        PraticaCategoriaFileUploadView.as_view(),
        name="pratica_categoria_file_upload",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/descrizione/",
        PraticaCategoriaFileDescriptionView.as_view(),
        name="pratica_categoria_file_description",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/elimina/",
        PraticaCategoriaFileDeleteView.as_view(),
        name="pratica_categoria_file_delete",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:pk>/file/scollega/",
        PraticaCategoriaFileUnlinkView.as_view(),
        name="pratica_categoria_file_unlink",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/aggiungi/",
        PraticaCategoriaAllegatoUploadView.as_view(),
        name="pratica_categoria_allegato_upload",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/scegli/",
        PraticaCategoriaAllegatoPickView.as_view(),
        name="pratica_categoria_allegato_pick",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/<int:pk>/file/",
        PraticaCategoriaAllegatoFileView.as_view(),
        name="pratica_categoria_allegato_file",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/<int:pk>/apri/",
        PraticaCategoriaAllegatoOpenView.as_view(),
        name="pratica_categoria_allegato_open",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/<int:pk>/elimina/",
        PraticaCategoriaAllegatoDeleteView.as_view(),
        name="pratica_categoria_allegato_delete",
    ),
    path(
        "<int:pratica_pk>/categorie/<int:categoria_pk>/allegati/<int:pk>/distruggi/",
        PraticaCategoriaAllegatoDestroyView.as_view(),
        name="pratica_categoria_allegato_destroy",
    ),
    path("<int:pratica_pk>/tecnici/nuovo/", TecnicoCreateView.as_view(), name="tecnico_create"),
    path("<int:pratica_pk>/tecnici/<int:pk>/modifica/", TecnicoUpdateView.as_view(), name="tecnico_update"),
    path("<int:pratica_pk>/tecnici/<int:pk>/elimina/", TecnicoDeleteView.as_view(), name="tecnico_delete"),
]
