from django.urls import path

from .views import (
    AnagraficaListView,
    AnagraficaCreateView,
    AnagraficaUpdateView,
    AnagraficaDetailView,
    AnagraficaDeleteView,
    ContattoCreateView,
    ContattoUpdateView,
    ContattoDeleteView,
    ComuneCreateView,
    ComuneDeleteView,
    ComuneJsonView,
    ComuneListView,
    ComuneUpdateView,
    IndirizzoCreateView,
    IndirizzoUpdateView,
    IndirizzoDeleteView,
    PersonaleAnagraficaCreateView,
    PersonaleAnagraficaUpdateView,
    PersonaleAnagraficaDeleteView,
    ProvinciaCreateView,
    ProvinciaDeleteView,
    ProvinciaListView,
    ProvinciaUpdateView,
)

app_name = "anagrafiche"

urlpatterns = [
    path("", AnagraficaListView.as_view(), name="anagrafica_list"),
    path("nuova/", AnagraficaCreateView.as_view(), name="anagrafica_create"),
    path("province/", ProvinciaListView.as_view(), name="provincia_list"),
    path("province/nuova/", ProvinciaCreateView.as_view(), name="provincia_create"),
    path("province/<int:pk>/modifica/", ProvinciaUpdateView.as_view(), name="provincia_update"),
    path("province/<int:pk>/elimina/", ProvinciaDeleteView.as_view(), name="provincia_delete"),
    path("comuni/", ComuneListView.as_view(), name="comune_list"),
    path("comuni/nuova/", ComuneCreateView.as_view(), name="comune_create"),
    path("comuni/<int:pk>/modifica/", ComuneUpdateView.as_view(), name="comune_update"),
    path("comuni/<int:pk>/elimina/", ComuneDeleteView.as_view(), name="comune_delete"),
    path("api/comuni/", ComuneJsonView.as_view(), name="comune_json"),
    path("<int:pk>/modifica/", AnagraficaUpdateView.as_view(), name="anagrafica_update"),
    path("<int:pk>/elimina/", AnagraficaDeleteView.as_view(), name="anagrafica_delete"),
    path("<int:anagrafica_pk>/contatti/nuovo/", ContattoCreateView.as_view(), name="contatto_create"),
    path("<int:anagrafica_pk>/contatti/<int:pk>/modifica/", ContattoUpdateView.as_view(), name="contatto_update"),
    path("<int:anagrafica_pk>/contatti/<int:pk>/elimina/", ContattoDeleteView.as_view(), name="contatto_delete"),
    path("<int:anagrafica_pk>/indirizzi/nuovo/", IndirizzoCreateView.as_view(), name="indirizzo_create"),
    path("<int:anagrafica_pk>/indirizzi/<int:pk>/modifica/", IndirizzoUpdateView.as_view(), name="indirizzo_update"),
    path("<int:anagrafica_pk>/indirizzi/<int:pk>/elimina/", IndirizzoDeleteView.as_view(), name="indirizzo_delete"),
    path("<int:anagrafica_pk>/personale/nuovo/", PersonaleAnagraficaCreateView.as_view(), name="personale_create"),
    path(
        "<int:anagrafica_pk>/personale/<int:pk>/modifica/",
        PersonaleAnagraficaUpdateView.as_view(),
        name="personale_update",
    ),
    path(
        "<int:anagrafica_pk>/personale/<int:pk>/elimina/",
        PersonaleAnagraficaDeleteView.as_view(),
        name="personale_delete",
    ),
    path("<int:pk>/", AnagraficaDetailView.as_view(), name="anagrafica_detail"),
]
