# Generated by Django 6.0.6 on 2026-07-07 21:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0003_contatto_indirizzo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('codice', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Codice')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('tipologia', models.CharField(blank=True, max_length=100, verbose_name='Tipologia')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('aperta', 'Aperta'), ('in_lavorazione', 'In lavorazione'), ('in_attesa_cliente', 'In attesa cliente'), ('in_attesa_esterna', 'In attesa esterna'), ('completata', 'Completata'), ('annullata', 'Annullata'), ('archiviata', 'Archiviata')], default='aperta', max_length=30, verbose_name='Stato')),
                ('priorita', models.CharField(choices=[('bassa', 'Bassa'), ('normale', 'Normale'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorita')),
                ('data_apertura', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data apertura')),
                ('data_scadenza', models.DateField(blank=True, null=True, verbose_name='Data scadenza')),
                ('data_chiusura', models.DateField(blank=True, null=True, verbose_name='Data chiusura')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pratiche', to='anagrafiche.anagrafica', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pratiche_assegnate', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Pratica',
                'verbose_name_plural': 'Pratiche',
                'ordering': ['-data_apertura', '-id'],
            },
        ),
    ]
