# Generated by Django 6.0.6 on 2026-07-07 21:48

from django.db import migrations, models


def normalize_tipologia(apps, schema_editor):
    Pratica = apps.get_model("pratiche", "Pratica")
    allowed = {
        "impianto_elettrico",
        "impianto_termico",
        "enea",
        "atex",
    }
    Pratica.objects.exclude(tipologia__in=allowed).update(tipologia="impianto_elettrico")


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_tipologia, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pratica',
            name='tipologia',
            field=models.CharField(choices=[('impianto_elettrico', 'Impianto elettrico'), ('impianto_termico', 'Impianto termico'), ('enea', 'ENEA'), ('atex', 'ATEX')], max_length=30, verbose_name='Tipologia'),
        ),
    ]
