# Generated by Django 6.0.6 on 2026-07-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0003_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='incarico',
            field=models.CharField(blank=True, max_length=150, verbose_name='Incarico'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='studio_appartenenza',
            field=models.CharField(blank=True, max_length=200, verbose_name='Studio di appartenenza'),
        ),
    ]
