# Generated by Django 6.0.6 on 2026-07-07 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0010_pratica_categoria_unique_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PraticaCategoriaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('percorso_relativo', models.CharField(max_length=500, verbose_name='Percorso relativo')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('pratica_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_metadati', to='pratiche.praticacategoria', verbose_name='Categoria pratica')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'File categoria pratica',
                'verbose_name_plural': 'File categorie pratica',
                'ordering': ['percorso_relativo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('pratica_categoria', 'percorso_relativo'), name='unique_file_categoria_pratica_attivo')],
            },
        ),
    ]
