# Generated by Django 6.0.6 on 2026-07-08 01:11

import apps.pratiche.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0011_praticacategoriafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicazionePratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('data_ora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e ora comunicazione')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('allegato', models.FileField(blank=True, upload_to=apps.pratiche.models.comunicazione_upload_to, verbose_name='File comunicazione')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicazioni', to='pratiche.pratica', verbose_name='Pratica')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Comunicazione pratica',
                'verbose_name_plural': 'Comunicazioni pratica',
                'ordering': ['-data_ora', '-id'],
            },
        ),
    ]
