# Generated by Django 6.0.6 on 2026-07-08 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0013_macrocategoriapratica_praticamacrocategoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='praticacategoria',
            options={'ordering': ['macro_categoria__denominazione', 'categoria__denominazione', 'versione'], 'verbose_name': 'Categoria pratica collegata', 'verbose_name_plural': 'Categorie pratica collegate'},
        ),
        migrations.RemoveConstraint(
            model_name='praticacategoria',
            name='unique_pratica_categoria_versione',
        ),
        migrations.AddField(
            model_name='praticacategoria',
            name='macro_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_collegamenti', to='pratiche.macrocategoriapratica', verbose_name='Macro-categoria'),
        ),
        migrations.AddConstraint(
            model_name='praticacategoria',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('macro_categoria__isnull', True)), fields=('pratica', 'categoria', 'versione'), name='unique_pratica_categoria_versione_senza_macro'),
        ),
        migrations.AddConstraint(
            model_name='praticacategoria',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('macro_categoria__isnull', False)), fields=('pratica', 'macro_categoria', 'categoria', 'versione'), name='unique_pratica_macro_categoria_categoria_versione'),
        ),
    ]
