# Generated by Django 6.0.6 on 2026-07-08 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_templates(apps, schema_editor):
    TemplatePratica = apps.get_model("pratiche", "TemplatePratica")
    for tipologia in ["impianto_elettrico", "impianto_termico", "enea", "atex"]:
        TemplatePratica.objects.get_or_create(tipologia=tipologia)


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0014_alter_praticacategoria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('tipologia', models.CharField(choices=[('impianto_elettrico', 'Impianto elettrico'), ('impianto_termico', 'Impianto termico'), ('enea', 'ENEA'), ('atex', 'ATEX')], max_length=30, unique=True, verbose_name='Tipologia')),
                ('categorie', models.ManyToManyField(blank=True, related_name='template_pratiche', to='pratiche.categoriapratica', verbose_name='Categorie singole')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('macro_categorie', models.ManyToManyField(blank=True, related_name='template_pratiche', to='pratiche.macrocategoriapratica', verbose_name='Macro-categorie')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Template pratica',
                'verbose_name_plural': 'Template pratiche',
                'ordering': ['tipologia'],
            },
        ),
        migrations.RunPython(create_default_templates, migrations.RunPython.noop),
    ]
