# Generated by Django 6.0.6 on 2026-07-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0015_templatepratica'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticacategoria',
            name='origine_template',
            field=models.BooleanField(default=False, verbose_name='Origine template'),
        ),
    ]
