# Generated by Django 6.0.6 on 2026-07-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0017_praticacategoriaallegato'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticacategoriafile',
            name='scollegato',
            field=models.BooleanField(default=False, verbose_name='Scollegato dalla pratica'),
        ),
    ]
