# Generated by Django 6.0.6 on 2026-07-08 13:31

import apps.pratiche.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0018_praticacategoriafile_scollegato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicazionepratica',
            name='allegato',
            field=models.FileField(blank=True, max_length=500, upload_to=apps.pratiche.models.comunicazione_upload_to, verbose_name='File comunicazione'),
        ),
        migrations.AlterField(
            model_name='praticacategoriaallegato',
            name='file',
            field=models.FileField(max_length=500, upload_to=apps.pratiche.models.pratica_categoria_allegato_upload_to, verbose_name='File'),
        ),
    ]
