# Generated by Django 6.0.6 on 2026-07-29 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0020_tipologiapratica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiotecnico',
            options={'ordering': ['denominazione'], 'verbose_name': 'Esterno', 'verbose_name_plural': 'Esterni'},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'Personale', 'verbose_name_plural': 'Personale'},
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='studio_appartenenza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tecnici', to='pratiche.studiotecnico', verbose_name='Esterno'),
        ),
    ]
