# Generated by Django 6.0.6 on 2026-09-04 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratiche', '0022_tecnico_anagrafica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatepratica',
            name='tipologia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='template_pratiche', to='pratiche.tipologiapratica', verbose_name='Tipologia'),
        ),
    ]
