# Generated by Django 6.0.6 on 2026-07-08 00:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pratiche', '0011_praticacategoriafile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneNotificaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('attiva', models.BooleanField(default=False, verbose_name='Attiva')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='Server SMTP')),
                ('porta', models.PositiveIntegerField(default=587, verbose_name='Porta')),
                ('usa_tls', models.BooleanField(default=True, verbose_name='Usa TLS')),
                ('usa_ssl', models.BooleanField(default=False, verbose_name='Usa SSL')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Password')),
                ('mittente', models.EmailField(blank=True, max_length=254, verbose_name='Mittente')),
                ('destinatari_default', models.TextField(blank=True, verbose_name='Destinatari predefiniti')),
                ('giorni_preavviso', models.PositiveSmallIntegerField(default=7, verbose_name='Giorni preavviso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Configurazione notifiche email',
                'verbose_name_plural': 'Configurazioni notifiche email',
            },
        ),
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('tipo', models.CharField(choices=[('evento', 'Evento'), ('scadenza', 'Scadenza'), ('lavoro', 'Lavoro')], default='lavoro', max_length=20, verbose_name='Tipo')),
                ('stato', models.CharField(choices=[('programmato', 'Programmato'), ('in_corso', 'In corso'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='programmato', max_length=20, verbose_name='Stato')),
                ('data_inizio', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data inizio')),
                ('ora_inizio', models.TimeField(blank=True, null=True, verbose_name='Ora inizio')),
                ('data_fine', models.DateField(blank=True, null=True, verbose_name='Data fine / scadenza')),
                ('ora_fine', models.TimeField(blank=True, null=True, verbose_name='Ora fine')),
                ('notifica_email', models.BooleanField(default=True, verbose_name='Notifica email')),
                ('notificato_il', models.DateTimeField(blank=True, null=True, verbose_name='Notificato il')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi_agenda', to='pratiche.pratica', verbose_name='Pratica')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Evento agenda',
                'verbose_name_plural': 'Eventi agenda',
                'ordering': ['data_inizio', 'ora_inizio', 'titolo'],
            },
        ),
    ]
