# Generated by Django 6.0.6 on 2026-07-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_configurazionenotificaemail_verifica_certificato_ssl'),
        ('pratiche', '0022_tecnico_anagrafica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoagenda',
            name='tecnici',
            field=models.ManyToManyField(blank=True, related_name='eventi_agenda', to='pratiche.tecnico', verbose_name='Personale'),
        ),
    ]
