# Generated by Django 6.0.6 on 2026-09-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_configurazione_servizio_intervallo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionenotificaemail',
            name='template_corpo',
            field=models.TextField(blank=True, default='Promemoria: {{titolo}}\n\nTipo: {{tipo}}\nPratica: {{pratica_codice}} - {{pratica_titolo}}\nCliente: {{cliente}}\nData: {{data}}\nOra: {{ora}}\n\n{{descrizione}}\n\nApri pratica: {{url_pratica}}', help_text="Testo dell'email di preavviso. Segnaposto disponibili: {{titolo}}, {{tipo}}, {{pratica_codice}}, {{pratica_titolo}}, {{cliente}}, {{data}}, {{ora}}, {{descrizione}}, {{url_pratica}}, {{giorni_preavviso}}, {{data_notifica}}.", verbose_name='Modello testo mail'),
        ),
        migrations.AddField(
            model_name='configurazionenotificaemail',
            name='template_oggetto',
            field=models.CharField(blank=True, default='[Securtek] Promemoria {{data}} - {{titolo}}', help_text='Usa segnaposto come {{titolo}}, {{data}}, {{pratica_codice}}.', max_length=300, verbose_name='Modello oggetto mail'),
        ),
    ]
